import photo from "./images";
const array = [
  {
    name: "The Book Thief",
    price: 6.99,
    genre: [
      "Novel",
      "Young Adult Fiction",
      "Historical Fiction",
      "Bildungsroman",
    ],
    avgrating: 4.61,
    author: "Markus Zusak",
    published: 2005,
    img: photo.bookthief,
  },
  {
    name: "To Kill a Mockingbird",
    price: 10.99,
    genre: [
      "Novel",
      "Bildungsroman",
      "Thriller",
      "Southern Gothic",
      "Domestic Fiction",
      "Legal Story",
    ],
    avgrating: 4.27,
    author: "Harper Lee",
    published: 1960,
    img: photo.mockingbird,
  },
  {
    name: "Animal Farm",
    price: 14.99,
    genre: [
      "Allegory",
      "Satire",
      "Fable",
      "Novella",
      "Roman à clef",
      "Dystopian Fiction",
      "Political Fiction",
    ],
    avgrating: 3.98,
    author: "George Orwell",
    published: 1945,
    img: photo.animalfarm,
  },
  {
    name: "Invisible Man",
    price: 19.49,
    genre: ["Novel", "Fiction", "Bildungsroman"],
    avgrating: 4.48,
    author: "Ralph Ellison",
    published: 1952,
    img: photo.invisibleman,
  },
  {
    name: "To The Lighthouse",
    price: 10.09,
    genre: ["Novel", "Fiction"],
    avgrating: 3.93,
    author: "Virginia Woolf",
    published: 1927,
    img: photo.tothelighthouse,
  },
  {
    name: "Lord of The Flies",
    price: 9.69,
    genre: ["Novel", "Allegory", "Young Adult Fiction"],
    avgrating: 3.52,
    author: "William Golding",
    published: 1954,
    img: photo.lordoftheflies,
  },
];
export { array };
