const books = [
  {
    name: "The Book Thief",
    price: 6.99,
    genre: [
      "Novel",
      "Young Adult Fiction",
      "Historical Fiction",
      "Bildungsroman",
    ],
    avgrating: 4.6,
    author: "Markus Zusak",
    published: 2005,
  },
  {
    name: "To Kill a Mockingbird",
    price: 10.99,
    genre: [
      "Novel",
      "Bildungsroman",
      "Thriller",
      "Southern Gothic",
      "Domestic Fiction",
      "Legal Story",
    ],
    avgrating: 4.27,
    author: "Harper Lee",
    published: 1960,
  },
  {
    name: "Animal Farm",
    price: 15.1,
    genre: [
      "Allegory",
      "Satire",
      "Fable",
      "Novella",
      "Roman à clef",
      "Dystopian Fiction",
      "Political Fiction",
    ],
    avgrating: 3.98,
    author: "George Orwell",
    published: 1945,
  },
  {
    name: "Invisible Man",
    price: 19.49,
    genre: ["Novel", "Fiction", "Bildungsroman"],
    avgrating: 4.5,
    author: "Ralph Ellison",
    published: 1952,
  },
  {
    name: "To The Lighthouse",
    price: 10.0,
    genre: ["Novel", "Fiction"],
    avgrating: 3.9,
    author: "Virginia Woolf",
    published: 1927,
  },
  {
    name: "Lord of The Flies",
    price: 9.69,
    genre: ["Novel", "Allegory", "Young Adult Fiction"],
    avgrating: 3.5,
    author: "William Golding",
    published: 1954,
  },
];
export { books };
