const array = [
  {
    name: "The Book Thief",
    price: 6.99,
    genre: [
      "Novel",
      "Young Adult Fiction",
      "Historical Fiction",
      "Bildungsroman",
    ],
    avgrating: 4.61,
    author: "Markus Zusak",
    published: 2005,
    img: `https://static-readingaustralia-com-au.s3.amazonaws.com/uploads/2018/01/The-Book-Thief-cover-image.jpg`,
  },
  {
    name: "To Kill a Mockingbird",
    price: 10.99,
    genre: [
      "Novel",
      "Bildungsroman",
      "Thriller",
      "Southern Gothic",
      "Domestic Fiction",
      "Legal Story",
    ],
    avgrating: 4.27,
    author: "Harper Lee",
    published: 1960,
    img: `https://i.pinimg.com/originals/0b/bf/b5/0bbfb59b4d5592e2e7fac9930012ce6d.jpg`,
  },
  {
    name: "Animal Farm",
    price: 14.99,
    genre: [
      "Allegory",
      "Satire",
      "Fable",
      "Novella",
      "Roman à clef",
      "Dystopian Fiction",
      "Political Fiction",
    ],
    avgrating: 4.02,
    author: "George Orwell",
    published: 1945,
    img: `https://i.pinimg.com/originals/a9/33/fa/a933fa4e5302778a02b48918bacb81db.jpg`,
  },
  {
    name: "Invisible Man",
    price: 19.49,
    genre: ["Novel", "Fiction", "Bildungsroman"],
    avgrating: 4.48,
    author: "Ralph Ellison",
    published: 1952,
    img: `https://s26162.pcdn.co/wp-content/uploads/2019/04/14395257572.jpg`,
  },
  {
    name: "To The Lighthouse",
    price: 10.09,
    genre: ["Novel", "Fiction"],
    avgrating: 3.93,
    author: "Virginia Woolf",
    published: 1927,
    img: `https://m.media-amazon.com/images/I/41GWqsNHAPL.jpg`,
  },
  {
    name: "Lord of The Flies",
    price: 9.69,
    genre: ["Novel", "Allegory", "Young Adult Fiction"],
    avgrating: 3.52,
    author: "William Golding",
    published: 1954,
    img: `https://m.media-amazon.com/images/I/51eeAWItwbL._AC_SY780_.jpg`,
  },
];
export { array };
